# Generated by Django 4.2.7 on 2023-11-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_customers_orderdetails_orders_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='product_images/'),
        ),
    ]
