# Generated by Django 4.2.7 on 2023-11-05 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_products_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='estimated_delivery_date',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='tracking_number',
        ),
        migrations.RemoveField(
            model_name='products',
            name='manufacturer',
        ),
    ]
