# Generated by Django 4.2.7 on 2023-11-05 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_orders_estimated_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='store/static/products/'),
        ),
    ]
