# Generated by Django 4.2.7 on 2023-11-05 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Cart',
        ),
    ]
