# Generated by Django 4.2.7 on 2023-11-05 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_product_cart_products_cart_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='date_of_birth',
        ),
    ]
