# Generated by Django 4.2.7 on 2023-11-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_customers_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='password',
            field=models.CharField(default='password', max_length=50),
        ),
    ]
