# Generated by Django 4.2.7 on 2023-11-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_customers_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
