# Generated by Django 4.2.7 on 2023-11-05 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_customers_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='password',
        ),
    ]
