# Generated by Django 4.2.7 on 2023-11-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_customers_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='subtotal',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='weight',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
    ]
