# Generated by Django 4.2.7 on 2023-11-06 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_orderdetails_subtotal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='additional_notes',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='size',
        ),
    ]
