# Generated by Django 4.2.7 on 2023-11-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_orderdetails_additional_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='product',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='product',
            field=models.ManyToManyField(to='store.products'),
        ),
    ]
