# Generated by Django 4.2.7 on 2023-11-06 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_orderdetails_product_orderdetails_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='product',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.products'),
        ),
    ]
